[package]
name = "libtortillas"
version = "0.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
serde_bencode = "^0.2.4"
serde = { version = "1.0", features = ["derive"] }
serde_qs = "0.14.0"
sha1 = {version = "0.10.6" }
hex = "0.4.3"
reqwest = "0.12.13"
serde_repr = "0.1.20"
rand = "0.9.0"
num_enum = "0.7.3"
tokio-stream = "0.1"
thiserror = "2.0.12"
tracing = "0.1.41"
async-trait = "0.1.88"
librqbit-utp = "0.2.3"
bitvec = "1.0.1"
webrtc = "0.12.0"
tokio-tungstenite = {version = "0.26.2", features=["rustls-tls-native-roots"]}
rustls = { version = "0.23.26"  }
tokio-rustls = "0.26.2"
futures-util = "0.3.31"

[dependencies.rustls-native-certs]
optional = true
version = "0.8.0"

[dependencies.webpki-roots]
optional = true
version = "0.26.0"

[dependencies.rustls-pki-types]
optional = true
version = "1.0"

[dev-dependencies]
tracing-test = "0.2.5"
