[package]
name = "libtortillas"
version = "0.0.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
atomic-time = "0.1"
serde_bencode = "^0.2.4"
serde-querystring = "0.3.0"
sha1 = "0.10.6"
hex = "0.4.3"
reqwest = "0.12.13"
serde_repr = "0.1.20"
rand = "0.9.0"
num_enum = "0.7.3"
tokio-stream = "0.1"
thiserror = "2.0.12"
async-trait = "0.1.88"
librqbit-utp = "0.6.2"
bitvec = "1.0.1"
futures = "0.3"
bencode = "0.1.16"
serde_with = "3.14.0"
tokio-retry2 = { version = "0.5.7", features = ["tracing"] }
async-stream = "0.3.6"
bytes = "1"

[dev-dependencies]
tracing-test = "0.2.5"
